trigger:
  branches:
    include:
    - master
    - 'validate/*'
    - 'release/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - .github/

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  codecov_token: 3941003f-415d-4860-a724-fe3a98c0d0c8
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages

jobs:
- template: azure-pipelines/build.yml
