trigger:
  branches:
    include:
    - master
    - validate/*
    - release/*
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  codecov_token: 3941003f-415d-4860-a724-fe3a98c0d0c8
  ci_feed: /e08c98c0-63d6-4dc6-80ca-944e4deaf3d2

jobs:
- job: Windows
  pool: 
    vmImage: windows-latest
  steps:
  - template: azure-pipelines/install-dependencies.yml

  - powershell: |
      dotnet tool install --tool-path .. nbgv --ignore-failed-sources
      ../nbgv cloud
    displayName: Set build number
    workingDirectory: src

  - template: azure-pipelines/dotnet.yml

- job: Linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: azure-pipelines/install-dependencies.yml
  - template: azure-pipelines/dotnet.yml

- job: macOS
  pool:
    vmImage: macOS-latest
  steps:
  - template: azure-pipelines/install-dependencies.yml
  - template: azure-pipelines/dotnet.yml

- job: WrapUp
  dependsOn:
  - Windows
  - Linux
  - macOS
  pool:
    vmImage: ubuntu-latest
  condition: succeededOrFailed()
  steps:
  - template: azure-pipelines/install-dependencies.yml
  - template: azure-pipelines/publish-codecoverage.yml
  - template: azure-pipelines/publish-deployables.yml
